version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - yarn
      - yarn run disable
  build:
    commands:
      - yarn run build

artifacts:
  files:
    - "*/*"
  base_directory: public
